//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caja___TalkLink.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int ID_Cliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string telefono { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Telefon_Alt { get; set; }
        public string Direccion { get; set; }
        public string Estado { get; set; }
    }
}
